### PR TITLE
Migrate CI to Github Actions

### PR DESCRIPTION
**Pull request by milt**
~~Let's see if we can run the tests publicly through GH actions.~~

We can! Note that I've broken up the actions and called them directly rather than using the makefile, to provide an extra layer of clarity in the github UI

### CODE REVIEW

**Review by kelvinqian00 — APPROVED** [review]
Given I know little about setting up CI, seeing that the CI works anyways is good enough for me.

**Comment by milt** [comment]
Kinda the point of the PR, to show how to do this for other OSS stuff too. Worth reading the yaml.

**Comment by kelvinqian00** [comment]
Indeed, this would help out with our other open source projects like Pan and Colossal.

**Comment by milt** [comment]
> Indeed, this would help out with our other open source projects like Pan and Colossal.

Exactly

**Review by cliffcaseyyet — APPROVED** [review]
cool. reminds me a lot of pipelines. Does it have branch selection too?

**Comment by milt** [comment]
> cool. reminds me a lot of pipelines. Does it have branch selection too?

@cliffcaseyyet it does indeed, it's decent, about as good as what we get in codebuild

**Pull request merged**
