### PR TITLE
Cljx to cljc

### PR DESCRIPTION
**Pull request by milt**
Move everything from cljx to cljc!
**Note that this won't be testable until speclj is updated to handle cljc!**

### CODE REVIEW

**Comment by canweriotnow** [comment]
Shall I put this on hold until your pull request updating speclj to handle cljc is ready?

**Comment by canweriotnow** [comment]
lol, specljc

**Comment by milt** [comment]
Yeah, put it on hold, looks like 3.3.0 on speclj still has problems, or my brain does: https://github.com/slagyr/speclj/issues/131

**Comment by milt** [comment]
Got things working a little better on this branch: https://github.com/yetanalytics/xapi-schema/tree/speclj_cljc_debug

By mirroring the way speclj's tests work. But things still don't work for vigilant tests.

**Comment by milt** [comment]
Good to go @canweriotnow! No automatic tests for now, and that's OK

**Comment by canweriotnow** [comment]
Well, it's green, and I believe you and Travis.

**Pull request merged**
