### PR TITLE
updated to allow empty strings and empty objects

### PR DESCRIPTION
**Pull request by FeLungs**
Patch to account for https://github.com/yetanalytics/xapi-schema/issues/65

### CODE REVIEW

**Comment by FeLungs** [comment]
@deathtenk this patch should resolve the disconnect we have been discussing. This PR will need to be approved, merged, and then deployed to take effect

**Comment by milt** [comment]
I'd like to make sure the conformance tests pass on an LRS using this validator before moving forward on this, I could swear there used to be a test that failed if you *didn't* omit them.

**Comment by FeLungs** [comment]
Sounds good

**Comment by FeLungs** [comment]
accounted for within #71

**Pull request closed without merging**
